// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package perfmon

import (
	"syscall"
	"unsafe"
)

var _ unsafe.Pointer

var (
	modpdh = syscall.NewLazyDLL("pdh.dll")

	procPdhOpenQuery             = modpdh.NewProc("PdhOpenQuery")
	procPdhAddCounter            = modpdh.NewProc("PdhAddCounter")
	procPdhCollectQueryData      = modpdh.NewProc("PdhCollectQueryData")
	procGetFormattedCounterValue = modpdh.NewProc("GetFormattedCounterValue")
)

func _PdhOpenQuery(dataSource *string, userData int, query *syscall.Handle) (err int) {
	r0, _, _ := syscall.Syscall(procPdhOpenQuery.Addr(), 3, uintptr(unsafe.Pointer(dataSource)), uintptr(userData), uintptr(unsafe.Pointer(query)))
	err = int(r0)
	return
}

func _PdhAddCounter(query syscall.Handle, counterPath string, userData int, counter *syscall.Handle) (err int) {
	var _p0 *byte
	_p0, _ = syscall.BytePtrFromString(counterPath)
	if _ != nil {
		return
	}
	return __PdhAddCounter(query, _p0, userData, counter)
}

func __PdhAddCounter(query syscall.Handle, counterPath *byte, userData int, counter *syscall.Handle) (err int) {
	r0, _, _ := syscall.Syscall6(procPdhAddCounter.Addr(), 4, uintptr(query), uintptr(unsafe.Pointer(counterPath)), uintptr(userData), uintptr(unsafe.Pointer(counter)), 0, 0)
	err = int(r0)
	return
}

func _PdhCollectQueryData(query syscall.Handle) (err int) {
	r0, _, _ := syscall.Syscall(procPdhCollectQueryData.Addr(), 1, uintptr(query), 0, 0)
	err = int(r0)
	return
}

func _PdhGetFormattedCounterValue(counter syscall.Handle, format int, counterType int, value PdhCounterValue) (err int) {
	r0, _, _ := syscall.Syscall6(procGetFormattedCounterValue.Addr(), 4, uintptr(counter), uintptr(format), uintptr(counterType), uintptr(value), 0, 0)
	err = int(r0)
	return
}
