- module: windows
  metricsets: ["perfmon"]
  enabled: true
  period: 1s
  hosts: ["localhost"]
  perfmon.counters:  
    - alias: "Prozessorzeit"
      query: "\\Prozessorinformationen(*)\\Prozessorzeit (%)"